name: Build Next.js application
on: push
jobs:
  build-project:
    name: Build Next.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install package
        run: npm install

      - name: Build project
        run: npm run build
