name: Build Next.js application
on: push
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install package
          uses: npm install

        - name: Build project
          run: npm run build